blank_issues_enabled: false
contact_links:
  - name: "\U0001F4E7 Discussions 讨论"
    url: https://github.com/junjiem/dify-plugin-repackaging/discussions
    about: General discussions and request help. 一般性讨论和请求帮助。